"""fix user table

Revision ID: 02b868dd20b2
Revises: 0ae54a7549e5
Create Date: 2025-03-13 00:03:23.250981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02b868dd20b2'
down_revision: Union[str, None] = '0ae54a7549e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
