"""add tg id in User

Revision ID: 0ae54a7549e5
Revises: ea5fb3944a0d
Create Date: 2025-03-12 23:57:35.008754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ae54a7549e5'
down_revision: Union[str, None] = 'ea5fb3944a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###
