"""ocp principle

Revision ID: 51ea7a0baf2d
Revises: 0e48d33599f3
Create Date: 2025-02-15 00:14:00.065699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ea7a0baf2d'
down_revision: Union[str, None] = '0e48d33599f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_provider',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('creds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('used_space', sa.BIGINT(), nullable=True),
    sa.Column('available_space', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.drop_index('ix_google_drive_email', table_name='google_drive')
    op.drop_table('google_drive')
    op.add_column('file_chunk', sa.Column('provider_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('file_chunk', sa.Column('provider_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'file_chunk', 'storage_provider', ['provider_id'], ['uid'])
    op.drop_column('file_chunk', 'drive_file_id')
    op.drop_column('file_chunk', 'drive_account')
    op.create_index(op.f('ix_file_info_user_id'), 'file_info', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_info_user_id'), table_name='file_info')
    op.add_column('file_chunk', sa.Column('drive_account', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('file_chunk', sa.Column('drive_file_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file_chunk', type_='foreignkey')
    op.drop_column('file_chunk', 'provider_id')
    op.drop_column('file_chunk', 'provider_file_id')
    op.create_table('google_drive',
    sa.Column('uid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('used_space', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('available_space', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uid'], name='google_drive_user_id_fkey'),
    sa.PrimaryKeyConstraint('uid', name='google_drive_pkey')
    )
    op.create_index('ix_google_drive_email', 'google_drive', ['email'], unique=True)
    op.drop_table('storage_provider')
    # ### end Alembic commands ###
