"""email not unique

Revision ID: ea5fb3944a0d
Revises: fedb153e6c94
Create Date: 2025-02-18 00:33:22.164559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ea5fb3944a0d'
down_revision: Union[str, None] = 'fedb153e6c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storage_provider', 'provider_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_storage_provider_email', table_name='storage_provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_storage_provider_email', 'storage_provider', ['email'], unique=True)
    op.alter_column('storage_provider', 'provider_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
