"""fresh

Revision ID: fedb153e6c94
Revises: 
Create Date: 2025-02-15 13:52:09.442584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fedb153e6c94'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=True)
    op.create_table('file_info',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.BIGINT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['firebase_uid'], ['user.firebase_uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_file_info_firebase_uid'), 'file_info', ['firebase_uid'], unique=False)
    op.create_table('storage_provider',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creds', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('used_space', sa.BIGINT(), nullable=True),
    sa.Column('available_space', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['firebase_uid'], ['user.firebase_uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_storage_provider_email'), 'storage_provider', ['email'], unique=True)
    op.create_index(op.f('ix_storage_provider_firebase_uid'), 'storage_provider', ['firebase_uid'], unique=False)
    op.create_table('file_chunk',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('provider_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('size', sa.BIGINT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file_info.uid'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['storage_provider.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_file_chunk_file_id'), 'file_chunk', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_chunk_file_id'), table_name='file_chunk')
    op.drop_table('file_chunk')
    op.drop_index(op.f('ix_storage_provider_firebase_uid'), table_name='storage_provider')
    op.drop_index(op.f('ix_storage_provider_email'), table_name='storage_provider')
    op.drop_table('storage_provider')
    op.drop_index(op.f('ix_file_info_firebase_uid'), table_name='file_info')
    op.drop_table('file_info')
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
