from .dashboard_view import get_dashboard_view
from .home_view import get_home_view
from .file_list_view import get_file_list_view
from .help_view import get_help_view
from .about_view import get_about_view
from .settings_view import get_settings_view
from .help_view import get_help_view
from .about_view import get_about_view
from .unlink_view import get_unlink_view